version: '2'
services:
  web:
    scale: 1
    health_check:
      # Which port to perform the check against
      port: 8080
      # For TCP, request_line needs to be '' or not shown
      # TCP Example:
      # request_line: ''
      request_line: GET /monitor/info HTTP/1.0
      # Interval is measured in milliseconds
      interval: 5000
      initializing_timeout: 40000
      reinitializing_timeout: 40000
      unhealthy_threshold: 3
      # Strategy for what to do when unhealthy
      # In this service, no action will occur when a container is found unhealthy
      strategy: none
      healthy_threshold: 2
      # Response timeout is measured in milliseconds
      response_timeout: 2000